version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: attendance-mongodb-dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: attendanceportal
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_dev:/data/db
    networks:
      - attendance-network-dev

  # Backend API Service (Development)
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: attendance-backend-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/attendanceportal?authSource=admin
      PORT: 5000
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
    ports:
      - "5000:5000"
    volumes:
      - ./Backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - attendance-network-dev
    command: npm run dev

  # Frontend Service (Development)
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.dev
    container_name: attendance-frontend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - attendance-network-dev
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

volumes:
  mongodb_data_dev:
    driver: local

networks:
  attendance-network-dev:
    driver: bridge
